#!/usr/bin/env python
# Filename : create_lilcms_subjects

from os import *

groups = ['GN_sub', 'EN_sub', 'SN_sub', 'ESN_sub', 'contributor','publisher']


for g in groups:
    cmd = "groupadd " + g
    system(cmd)

subjects= []
for i in range(25):
    char = 's' + str(i+1)
    subjects.append(char)

GN_sub = subjects[0:10]
EN_sub = subjects[10:13]
SN_sub = subjects[13:18]
ESN_sub = subjects[18:20]
contributors = subjects[20:24]
publishers = subjects[24:]

for s in GN_sub:
    cmd1 = "semanage user -a -L s0 -r s0-s0:c0.c1023 -R 'staff_r sysadm_r system_r unconfined_r' " + s + "_u"
    cmd2 = "useradd -m -p `openssl passwd -1 " + s + "` -Z " + s + "_u -g GN_sub " + s
    cmd3 = "usermod -g wheel " + s
    system(cmd1)
    system(cmd2)
    system(cmd3)


for s in EN_sub:
    cmd1 = "semanage user -a -L s0 -r s0-s0:c0.c1023 -R 'staff_r sysadm_r system_r unconfined_r' " + s + "_u"
    cmd2 = "useradd -m -p `openssl passwd -1 " + s + "` -Z " + s + "_u -g EN_sub " + s
    cmd3 = "usermod -g wheel " + s
    system(cmd1)
    system(cmd2)
    system(cmd3)


for s in SN_sub:
    cmd1 = "semanage user -a -L s0 -r s0-s0:c0.c1023 -R 'staff_r sysadm_r system_r unconfined_r' " + s + "_u"
    cmd2 = "useradd -m -p `openssl passwd -1 " + s + "` -Z " + s + "_u -g SN_sub " + s
    cmd3 = "usermod -g wheel " + s
    system(cmd1)
    system(cmd2)
    system(cmd3)

for s in ESN_sub:
    cmd1 = "semanage user -a -L s0 -r s0-s0:c0.c1023 -R 'staff_r sysadm_r system_r unconfined_r' " + s + "_u"
    cmd2 = "useradd -m -p `openssl passwd -1 " + s + "` -Z " + s + "_u -g ESN_sub " + s
    cmd3 = "usermod -g wheel " + s
    system(cmd1)
    system(cmd2)
    system(cmd3)

for s in contributors:
    cmd1 = "semanage user -a -L s0 -r s0-s0:c0.c1023 -R 'staff_r sysadm_r system_r unconfined_r' " + s + "_u"
    cmd2 = "useradd -m -p `openssl passwd -1 " + s + "` -Z " + s + "_u -g contributor " + s
    cmd3 = "usermod -g wheel " + s
    system(cmd1)
    system(cmd2)
    system(cmd3)


for s in publishers:
    cmd1 = "semanage user -a -L s0 -r s0-s0:c0.c1023 -R 'staff_r sysadm_r system_r unconfined_r' " + s + "_u"
    cmd2 = "useradd -m -p `openssl passwd -1 " + s + "` -Z " + s + "_u -g publisher " + s
    cmd3 = "usermod -g wheel " + s
    system(cmd1)
    system(cmd2)
    system(cmd3)
